export * from './Login'
export * from './Register'
export * from './Detail'
export * from './Ticketroom'
export * from './Profile'
export * from './Home'
export * from './TestHome'
export * from './Account'